version: "3"
services:
  user_management-service:
    build:
      context: ./User_Management
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty1234
      - MYSQL_DATABASE=devoteam_user  

  ui:
   build:
    context: ./UI
    dockerfile: Dockerfile
   ports:
    - "3000:3000"
   
