job('User-Management-Servcie-Via-DSL') {
    description("UserManagement Service job generated by the DSL on ${new Date()}, DevoTeam github")
    scm {
        git("https://github.com/airavata-courses/DevoTeam.git", 'Develop')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'User_Management/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
